### ISSUE TITLE
Initial Name Type Start

### ISSUE THREAD

**Issue by portermichael** [musflood/portfolio#5]
It might be worth reconsidering the timing of the initial name type start.

https://github.com/musflood/portfolio/blob/master/scripts/mainView.js
mainView.js - line 74
$(document).ready(function() {
  mainView.handleMenuArrowClick();
  mainView.handleMenuTabClick();
  mainView.typeOutWords($('#name-card .text-to-write'), 2000, 300);
});

**Comment by musflood** [comment]
Made it FASTER!
