### ISSUE TITLE
Picture color on box?

### ISSUE THREAD

**Issue by portermichael** [musflood/portfolio#6]
It might be helpful to have the picture highlight when someone scrolls into the box, not just when they hover over the picture. This would be useful because some people may miss the hovering over the picture as they go to "Read Description"

https://github.com/musflood/portfolio/blob/master/styles/modules.css
line 152
.project-image canvas:hover {
  opacity: 0;
}

**Comment by musflood** [comment]
Changed. Works much nicer.
